// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsrFnjCuwpSauyey1EWjCg75VEPDB6Aw',
    appId: '1:491712482003:android:63ed1d49b20294cdeb2226',
    messagingSenderId: '491712482003',
    projectId: 'suffa-app-497e8',
    storageBucket: 'suffa-app-497e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcyBecWftMKURmoTWQ2tOTI_tSgwOQZZE',
    appId: '1:491712482003:ios:c63377a8bcf94106eb2226',
    messagingSenderId: '491712482003',
    projectId: 'suffa-app-497e8',
    storageBucket: 'suffa-app-497e8.appspot.com',
    androidClientId: '491712482003-63j0rndu19dhe5ur9gj36p2s3pptr44n.apps.googleusercontent.com',
    iosClientId: '491712482003-bbepqb4dnuvkunt0ngog9ljoknejm4sf.apps.googleusercontent.com',
    iosBundleId: 'com.MHDevs.suffaApp',
  );
}
